### PR TITLE
Added handling of score submission for new ScoreSaber mod

### PR DESCRIPTION
**Pull request by Shadnix-was-taken**
Implementation done based on information by Zingabopp and Umbranox

### CODE REVIEW

**Comment by Shadnix-was-taken** [comment]
Tested on 1.6.1 and working based on the ScoreSaber status messages on the right panel. Made under the assumption that ScoreSaber will subscribe to didFinish on level start, which seems to be the case.

**Comment by Gordin** [comment]
Just curious, will this fix score submissions by BailOutMode? And if it does, will this also prevent BeatSaber from saving a replay? I passed Reality Check for the first time yesterday only to find out that I don't have a replay for my pass and also no entry in ScoreSaber because apparently 6 days ago I played the song with BailOutMode on, failed, but it saved a replay and submitted the score anyway :(

**Comment by Shadnix-was-taken** [comment]
If BailOutMode uses BS_Utils for disabling score submission (which I think it does based on the source I could find after a quick Discord search in #pc-mods), then yes, this will now disable score submission when bailed out as intended. The version currently distributed via BeatMods/ModAssistant already includes this patch.

As for the submitted score, that obviously won't be fixed retroactively. So I guess for a new score to upload and replay to save you probably have to beat the score currently listed. But this is just a guess as I don't know the internals of ScoreSaber.

**Comment by Gordin** [comment]
Oh, I didn't realize the version on BeatMods already had this patch. I figured if this pull request is still open and your and Kylemcs repository don't have any new releases listed on github, it would still be a WIP. I guess I'm safe from wrong submissions in the future then :) Thanks ^^

**Comment by Shadnix-was-taken** [comment]
Merged master to resolve existing merge conflicts that showed up after two other pull requests were merged.

**Comment by Shadnix-was-taken** [comment]
Closing this, because the changes were merged with #15

**Pull request closed without merging**
